version: '3.9'

services:
  db:
    image: portainer/portainer:latest
    restart: always
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
