version: '3.9'

services:
  db:
    image: mysql:8.0.25
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - MYSQL_DATABASE=youngha
      - MYSQL_ROOT_PASSWORD=youngha
      - TZ=Asia/Seoul
    volumes:
      - /home/ec2-user/volume/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
